# Generated by Django 5.2.3 on 2025-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_username', models.CharField(max_length=30)),
                ('candidate_password', models.CharField(max_length=30)),
                ('candidate_saltuation', models.CharField(default='', max_length=7)),
                ('candidate_first_name', models.CharField(max_length=30)),
                ('candidate_middle_name', models.CharField(default='', max_length=30)),
                ('candidate_last_name', models.CharField(max_length=30)),
                ('candidate_initials', models.CharField(default='', max_length=10)),
                ('candidate_gender', models.CharField(default='Prefer not to say', max_length=20)),
                ('candidate_affiliation', models.CharField(default='', max_length=100)),
                ('candidate_signature', models.CharField(default='', max_length=30)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_orcid_id', models.CharField(default='')),
                ('candidate_website_url', models.CharField(default='')),
                ('candidate_phone_number', models.CharField(max_length=15)),
                ('candidate_fax_number', models.CharField(default='')),
                ('candidate_mailing_address', models.CharField(default='')),
                ('candidate_country', models.CharField()),
                ('candidate_bio_statement', models.TextField(default='')),
            ],
        ),
    ]
